In [1]:
# to do , I am using 2 different computational graphs, so need 2 different sessions
#[ done ] 

# use rnn to condense features into a single feature vector
#  [ pending ]


In [2]:
from __future__ import print_function
import tensorflow as tf
import numpy as np
from scipy.io import wavfile
import six
#import tensorflow as tf

import vggish_input
import vggish_params
import vggish_postprocess
import vggish_slim

/home/saurabh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
num_classes=4
data_base_directory='data/datav2/'
alphabet_dict={0:'A' , 1:'B' , 2:'C' , 3:'D' , 4:'E', 5:'F' , 6:'G' ,7 :'H' , 8:'I', 9:'J'}


In [4]:
def process_function(input):
  
  

  input=data_base_directory + str(input ,'utf-8')
  #print(str(input,'utf-8'))

 

  for i in range(num_classes):
     if alphabet_dict[i] in input:
         y=int(i)

  #if 'A' in str(input,'utf-8'):
   #     y=0
 


  
    
  return  input,y


In [5]:
logfilepath='data/dataset.txt'
dataset = tf.data.TextLineDataset(logfilepath).shuffle(buffer_size=200) #.map(map_function)

dataset = dataset.map(
    lambda filename: tuple(tf.py_func(
        process_function, [filename],  [tf.string,tf.int64])))

dataset=dataset.batch(1)


# In[25]:


iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()


# In[28]:

with tf.Session() as sess:
    sess.run(iterator.initializer)
    for i in range(200):
      value = sess.run(next_element[0])
      print(value)


[b'data/datav2/20_54_21011B.wav']
[b'data/datav2/20_50_46073A.wav']
[b'data/datav2/20_50_46041A.wav']
[b'data/datav2/20_54_21006B.wav']
[b'data/datav2/20_50_46033A.wav']
[b'data/datav2/20_48_00007A.wav']
[b'data/datav2/20_50_46099A.wav']
[b'data/datav2/20_48_00022A.wav']
[b'data/datav2/20_50_46106A.wav']
[b'data/datav2/20_50_46025A.wav']
[b'data/datav2/20_50_46118A.wav']
[b'data/datav2/20_54_21002B.wav']
[b'data/datav2/20_48_00019A.wav']
[b'data/datav2/20_50_46027A.wav']
[b'data/datav2/20_50_46059A.wav']
[b'data/datav2/20_48_00008A.wav']
[b'data/datav2/20_50_46095A.wav']
[b'data/datav2/20_50_46101A.wav']
[b'data/datav2/20_48_00009A.wav']
[b'data/datav2/20_50_46064A.wav']
[b'data/datav2/20_54_21041B.wav']
[b'data/datav2/20_50_46070A.wav']
[b'data/datav2/20_50_46058A.wav']
[b'data/datav2/20_50_46100A.wav']
[b'data/datav2/20_50_46086A.wav']
[b'data/datav2/20_50_46038A.wav']
[b'data/datav2/20_50_46060A.wav']
[b'data/datav2/20_50_46091A.wav']
[b'data/datav2/20_50_46076A.wav']
[b'data/datav2

In [6]:
# Parameters
learning_rate = 0.01
num_steps = 500
batch_size = 2
display_step = 100

# Network Parameters
n_hidden_1 = 256 # 1st layer number of neurons
n_hidden_2 = 256 # 2nd layer number of neurons
num_input = 128 # MNIST data input (img shape: 28*28)
#num_classes = 5 # MNIST total classes (0-9 digits)

# tf Graph input
X = tf.placeholder(tf.float32, [None, num_input])
Y = tf.placeholder(tf.int32, [None])


In [7]:
# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([num_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, num_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([num_classes]))
}

In [8]:
# Create model
def neural_net(x):
    # Hidden fully connected layer with 256 neurons
    layer_1 =  tf.nn.relu (tf.add(tf.matmul(x, weights['h1']), biases['b1']))
    # Hidden fully connected layer with 256 neurons
    layer_2 =  tf.nn.relu(tf.add(tf.matmul(layer_1, weights['h2']), biases['b2']))
    # Output fully connected layer with a neuron for each class
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer

In [9]:
# Construct model
Logits = neural_net(X)

Logits = tf.Print(Logits, [Logits,tf.shape(Logits)], message="This is a: ")

# Define loss and optimizer
#loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
 #   logits=logits, labels=Y))
prediction = tf.nn.softmax(Logits)

optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=Y, logits=Logits))
train_op = optimizer.minimize(cost)

# Evaluate model (with test logits, for dropout to be disabled)
correct_pred = tf.equal(tf.argmax(Logits, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))



# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

In [10]:
g_1 = tf.Graph()
with g_1.as_default():
  

                
                
  

  # Sessions created in this scope will run operations from `g_1`.
                sess1 = tf.Session()
        
                vggish_slim.define_vggish_slim(training=False)
                vggish_slim.load_vggish_slim_checkpoint(sess1, 'vggish_model.ckpt')
                features_tensor = sess1.graph.get_tensor_by_name(
                vggish_params.INPUT_TENSOR_NAME)
                embedding_tensor = sess1.graph.get_tensor_by_name(
                vggish_params.OUTPUT_TENSOR_NAME)



INFO:tensorflow:Restoring parameters from vggish_model.ckpt


In [ ]:
# Start training
with tf.Session() as sess:
                sess.run(init)

   
                sess.run(iterator.initializer)

               
                
                examples_batch = vggish_input.wavfile_to_examples('data/vinay.wav')
                print(examples_batch.shape)

                # Prepare a postprocessor to munge the model embeddings.
                pproc = vggish_postprocess.Postprocessor('vggish_pca_params.npz')
                
               
    # Run inference and postprocessing.
                [embedding_batch] = sess1.run([embedding_tensor],
                                 feed_dict={features_tensor: examples_batch})
                print(embedding_batch.shape)
                postprocessed_batch = pproc.postprocess(embedding_batch)
                print(postprocessed_batch.shape)
    
              
              # train single example
                _ , c,l = sess.run([train_op, cost, Logits], feed_dict={X: postprocessed_batch,Y: Next_element[1] })
            
                 
                print(l.shape)
                print(c)
                #print(pre)
      #          print(p)
               
               
              
          
   
        
                
    # Save model weights to disk
   # save_path = saver.save(sess, model_path)
    #print("Model saved in file: %s" % save_path)   

In [17]:
# Start training
with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch in range(num_steps):
        avg_cost = 0.
        
        
        sess.run(iterator.initializer)
        while True:
            try:
                Next_element=sess.run(next_element)
                input_wav_file_name=str(Next_element[0][0],'utf-8')
                print(input_wav_file_name)
                
                examples_batch = vggish_input.wavfile_to_examples(input_wav_file_name)
                print(examples_batch.shape)

                # Prepare a postprocessor to munge the model embeddings.
                pproc = vggish_postprocess.Postprocessor('vggish_pca_params.npz')
                
               
    # Run inference and postprocessing.
                [embedding_batch] = sess1.run([embedding_tensor],
                                 feed_dict={features_tensor: examples_batch})
                print(embedding_batch.shape)
                postprocessed_batch = pproc.postprocess(embedding_batch)
                print(postprocessed_batch.shape)
                  
                #y_temp=np.zeros(3)
                    
                y_temp=np.append( Next_element[1], [ Next_element[1] ,Next_element[1] ]  )
                
                print(y_temp)

              # train single example
                _ , c,l = sess.run([train_op, cost, Logits], feed_dict={X: postprocessed_batch,Y: y_temp })
            
                 
                print(l.shape)
                print(c)
                #print(pre)
      #          print(p)
               
               
              
            except tf.errors.OutOfRangeError:
              break
   
        
                
    # Save model weights to disk
   # save_path = saver.save(sess, model_path)
    #print("Model saved in file: %s" % save_path)   

data/datav2/20_48_00018A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
0.0
data/datav2/20_48_00006A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
0.0
data/datav2/20_54_21022B.wav
(3, 96, 64)
(3, 128)
(3, 128)
[1 1 1]
(3, 4)
127457.77
data/datav2/20_54_21019B.wav
(3, 96, 64)
(3, 128)
(3, 128)
[1 1 1]
(3, 4)
0.0
data/datav2/20_48_00016A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
380674.84
data/datav2/20_50_46056A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
40322.95
data/datav2/20_54_21026B.wav
(3, 96, 64)
(3, 128)
(3, 128)
[1 1 1]
(3, 4)
0.0
data/datav2/20_50_46071A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
2672.7395
data/datav2/20_50_46006A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
0.0
data/datav2/20_50_46091A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
0.0
data/datav2/20_50_46014A.wav
(3, 96, 64)
(3, 128)
(3, 128)
[0 0 0]
(3, 4)
0.0
data/datav2/20_54_21021B.wav
(3, 96, 64)
(3, 128)
(3, 128)
[1 1 1]
(3, 4)
53010.8
data/datav2/20_50_46017A.wav
(3, 96, 

InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [2,4] and labels shape [3]
	 [[Node: SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Print, _arg_Placeholder_1_0_1)]]

Caused by op 'SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits', defined at:
  File "/home/saurabh/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saurabh/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-e476081f151b>", line 12, in <module>
    cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=Y, logits=Logits))
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1964, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4804, in _sparse_softmax_cross_entropy_with_logits
    labels=labels, name=name)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/saurabh/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [2,4] and labels shape [3]
	 [[Node: SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Print, _arg_Placeholder_1_0_1)]]


In [ ]:
# Start training
with tf.Session() as sess:

    # Run the initializer
    sess.run(init)

    for step in range(1, num_steps+1):
        batch_x, batch_y = mnist.train.next_batch(batch_size)
        # Run optimization op (backprop)
        sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
        if step % display_step == 0 or step == 1:
            # Calculate batch loss and accuracy
            loss, acc = sess.run([loss_op, accuracy], feed_dict={X: batch_x,
                                                                 Y: batch_y})
            print("Step " + str(step) + ", Minibatch Loss= " + \
                  "{:.4f}".format(loss) + ", Training Accuracy= " + \
                  "{:.3f}".format(acc))

    print("Optimization Finished!")

    # Calculate accuracy for MNIST test images
    print("Testing Accuracy:", \
        sess.run(accuracy, feed_dict={X: mnist.test.images,
                                      Y: mnist.test.labels}))